### ISSUE TITLE
Set up code linting

### ISSUE THREAD

**Issue by alexdovzhanyn** [UltraDark/ultradark_core#31]
As the codebase grows and more people begin contributing, it will become increasingly difficult to keep an eye on code style / best practices. To make this easier, let's use a code linter to automate some of the low-hanging fruit. Lets use [credo](https://github.com/rrrene/credo) for this

**Comment by Zac-Garby** [comment]
Just had a look at credo - it looks really cool. Is the idea to automatically run credo whenever someone makes a PR?

**Comment by yordis** [comment]
@Zac-Garby I am working on that.
