### ISSUE TITLE
Add formatter to the project

### ISSUE THREAD

**Issue by yordis** [UltraDark/ultradark_core#33]
- https://hexdocs.pm/mix/master/Mix.Tasks.Format.html

Probably use Travis for checking that people ran the formatter.

**Comment by alexdovzhanyn** [comment]
Im not sure I understand. Why do people need to run this formatter?

**Comment by yordis** [comment]
@alexdovzhanyn because you will no need to discuss about code formatting style, it auto fix your code and you keep consistency in your project.

I notice that you dont like to put parenthesis in functions calls (and that is fine) but Elixir suggest you to put parenthesis on functions calls, but if your habit coming from Ruby is not to use you could relay on `mix format` to do tedious work for you.

It removes friction pretty much, that is why you would use it.

**Comment by yordis** [comment]
@alexdovzhanyn check how many parenthesis the formatter added for you because you should be using it on the PR
