### ISSUE TITLE
Consistent function naming in Validator

### ISSUE THREAD

**Issue by Zac-Garby** [UltraDark/ultradark_core#35]
In the validator, some functions end in question marks and some don't, where really they all should or they all shouldn't. For example, there's `valid_hash/1` and `valid_coinbase?/1`. They both check if something's valid, but aren't consistent in their names.

**Comment by afbresley** [comment]
I think if the function only returns a boolean, then the question mark is appropriate. I'll follow this paradigm as I edit!
